#spring.datasource.url = jdbc:mysql://localhost:3307/festival_app
#spring.datasource.username=root
#spring.datasource.password=root
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
#
#server.port= 9000

spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/festival_app?serverTimezone=Europe/Amsterdam
    username: root
    password: root
    continue-on-error: false
    initialization-mode: never
#    this might be tomcat
    dbcp2:
      initial-size: 0
      time-between-eviction-runs-millis: 5000
      min-evictable-idle-time-millis: 5000
      min-idle: 0

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:

        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hbm2ddl:
          #change this to update to auto update tables
          auto: update
    show-sql: true
#        temp:
#          use_jdbc_metadata_defaults: false



server:
  port: 9000
